### ISSUE TITLE
Web3 Async API Tracking Issue

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1413]
Copy/paste from #1161, but with checkboxes and slightly more granularity. These will likely become their own issues.

- [x] Replace api methods with instances of a Method class, with a middleware like layer for formatting/normalizing/validating method input/output.

- [ ] Reduce middlewares to only those that make calls to the web3 api, moving the formatting middlewares to the Method input/output formatters.

- [ ] Separate async and sync execution pathway through RequestManagers -> middlewares -> providers.
  - Async Providers:
    - [x] HTTPProvider
    - [ ] IPCProvider
    - [x] WebsocketProvider
  - Async Versions of each Module
    - [x] Eth,
    - [x] Net
    - [x] Version
    - [x] ~~Parity Personal~~
    - [x] ~~Parity Shh~~
    - [x] Geth Admin
    - [ ] Geth Miner
    - [x] Geth Personal
    - [x] ~~Geth Shh~~
    - [x] Geth Tx Pool
    - [x] ~~Testing~~

**Comment by dbfreem** [comment]
@kclowes  I was thinking about taking on one of these Async additions if it didn't turn into a mountain of work. I had one question. 

On the Geth one above I see there is Admin, Miner, Personal, Shh, **TxPool**. I looked at the [docs](https://web3py.readthedocs.io/en/latest/web3.geth.html#gethtxpool-api) on how these methods are used. When I try to run inspect or status (see below code) in TxPool module I get `the method txpool_inspect does not exist/is not available'`. At first glance it looks like this is because only the Personal and Admin modules are wired up in [geth.py](https://github.com/ethereum/web3.py/blob/master/web3/geth.py#L140). 

Is the documentation wrong here or am I missing something

```
from web3 import HTTPProvider, Web3

web3 = Web3(HTTPProvider("http://127.0.0.1:8545"))
web3.isConnected()
print(web3.geth.txpool.inspect())
```

**Comment by kclowes** [comment]
@dbfreem that error message is coming back from your node. You’ll need to be attached to a local Geth node to have access to those methods. Sometimes you also need a flag on startup to have access to those modules on the Geth side. Running ‘geth —help’ should show the commands you need. It don’t remember the exact command off the top of my head but it’s something like ‘—http.api=personal’

**Comment by rencryptofish** [comment]
are all of the above outstanding tasks?

**Comment by dbfreem** [comment]
I was looking at asyncing parity but noticed there are no test for it. What is the strategy for async on parity code?
