### ISSUE TITLE
v6 Breaking Changes

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1416]
Now that v5 stable is out, it's time to start collecting a list of breaking changes that we might like to see in v6. I'll update this issue as they come up.

Outstanding breaking tasks:
- [x] Python 3.11 Support - #2699 
- [x] Remove Infura auto provider logic from within web3 ~~and make a template for new auto providers to use. See issue https://github.com/ethereum/web3.py/issues/1736~~ (#2706)
- [x] Remove `SolidityError` in favor of the more generic `ContractLogicError`. See issue #1901 
- [x] Remove camelCase function names in favor of snake_case. See #2598
- [x] Remove Parity module (via #2718)
- [x] Remove version module (see #2729)
- [x] Make ipfshttpclient opt-in. (See #2730 which closes #2629)
- [x] Remove `start_rpc` and `stop_rpc` from `geth.admin` module (see #2731)
- [x] Standardize `apply_formatter_to_array` functions. See #1902
- [x] Custom web3py exceptions inherit from Web3Exception. See #1478 
- [x] Enable strict bytes length checking by default. See issue #1419 and #1154.
- [x] Don't allow users to pass bytestrings to contract functions if the bytestring is the wrong length. As it stands, if a bytestring is shorter than the required length, we pad it. If it is longer, we throw an error. See issue #1903.
- [x] Raise specific web3 error rather than `ValueError` when method isn't available on the node: https://github.com/ethereum/web3.py/issues/2448
- [x] Standardize default value for block_identifier in eth.call and ContractFunctions.call. Change made in https://github.com/ethereum/web3.py/pull/2335 already, just needs tests.
- [x] Opt in or out of `dict` to `AttributeDict` conversion via middleware choice. See #1656.
- [x] Rich tuple decoder #1353 
- [x] Clean up Async typing

_shouldn't_ be breaking: 
- [x] Clean up AsyncHTTPProvider instantiation. - See #2736
- [x] Rearrange `web3/eth.py` into separate file. See #2753 
- [x] Remove dependency upper limits - #2648
- [x] Rearrange `contract.py` into separate files. See #2567
- [x] v6 Migration Guide

**Comment by kclowes** [comment]
All custom web3 exceptions should inherit from Web3Exception. See #1478

**Comment by kclowes** [comment]
The eth-utils and web3 `apply_formatter_to_array` functions are slightly different. We should standardize on one or the other (probably the eth-utils version). The `apply_formatter_to_array` function in web3 converts the return value to an array and the eth-utils version does not.

**Comment by kclowes** [comment]
Since `from` is a reserved word, change `from` to `sender` where appropriate.

**Comment by carver** [comment]
Looks like the #1419 plan is to enable strict bytes length checking by default. At which point I think #1154 could be closed.

**Comment by kclowes** [comment]
Remove Infura auto provider logic from within web3 and make a template for new auto providers to use. See issue #1736

**Comment by marcgarreau** [comment]
Whisper is officially out of Geth distros ([latest release notes](https://github.com/ethereum/go-ethereum/releases/tag/v1.9.21)), so we probably ought to drop support too.

**Comment by marcgarreau** [comment]
v6 is a probably a good time to reflect on some client namespace topics, given:
- Parity is now OpenEthereum (and has been for a while)
- Both Parity and OE clients are in the wild
- Soon™, OE is set to diverge significantly from Parity, see: [recent blog post](https://medium.com/openethereum/vision-for-openethereum-ex-parity-client-eb7b11f6eef8)
- Other clients on the sidelines: Nethermind, Trinity, Turbo-Geth, ...?
- Desire to encourage client diversity

**Comment by kclowes** [comment]
Move `get_event_data` and `get_function_info` to the public API. Related issue: #1596

**Comment by kclowes** [comment]
The `SolidityError` that was introduced in #1585 should be more generic since more than one language has an `assert`/`revert` feature and we want to support more than just Solidity.

**Comment by kclowes** [comment]
Drop python 3.6 support? Python 3.6 will no longer be supported after 12/23/21. See: https://endoflife.date/python

**Comment by kclowes** [comment]
Remove camelCase methods in `eth` and `geth` modules. Consider making `buildTransaction` -> `build_transaction`, `estimateGas` -> `estimate_gas`

**Comment by kclowes** [comment]
Move websockets dependency to 10.0+ which means we can get rid of loop argument deprecation warnings. Dependent on dropping python 3.6

**Comment by kclowes** [comment]
Standardize default value for `block_identifier` in `eth.call` and `ContractFunctions.call`. Change made in #2335 already, just needs tests.

**Comment by kclowes** [comment]
Add black

**Comment by Harmouch101** [comment]
It would be great to integrate `pre-commit` within `tox` to make the `dev` process faster & easier in a way that developers are not required to manually fix linting issues. To do so, The following modifications would be introduced to `tox.ini`:

```yml
[testenv:lint]
basepython=python3
skip_install = true
deps = pre-commit
commands=
    pre-commit run --all-files --show-diff-on-failure
```

instead of:

```yml
[testenv:lint]
basepython=python
extras=linter
commands=
    flake8 {toxinidir}/web3 {toxinidir}/ens {toxinidir}/ethpm {toxinidir}/tests --exclude {toxinidir}/ethpm/ethpm-spec
    isort --recursive --check-only --diff {toxinidir}/web3/ {toxinidir}/ens/ {toxinidir}/ethpm/ {toxinidir}/tests/
    mypy -p web3 -p ethpm -p ens --config-file {toxinidir}/mypy.ini
```


And then add code formatters and fixers in the `pre-commit` config file(`.pre-commit-config.yaml`) as local hooks like:

```yml
  - repo: local
    hooks:
      - id: flake8
        name: Check flake8 syntax
        entry: flake8 web3 ens ethpm tests --exclude ethpm/ethpm-spec
        pass_filenames: false
        language: system
        types: [python]
      - id: isort
        name: Sort imports alphabetically
        entry: isort --recursive --check-only --diff web3 ens ethpm tests
        pass_filenames: false
        language: system
        types: [python]
      - id: mypy
        name: Check mypy static types match
        entry: mypy -p web3 -p ethpm -p ens --config-file mypy.ini
        pass_filenames: false
        language: system
        types: [python]
```

To add `black` as @kclowes did in [PR:#2345](https://github.com/ethereum/web3.py/pull/2345), just add a new local hook in a similar fashion to the previous ones:

```yml
      - id: black
        name: Run black code formatter
        entry: black ethpm --exclude ethpm/ethpm-spec web3 ens tests --check
        pass_filenames: false
        language: system
        types: [python]
```

`pre-commit` is equipped with useful built-in fixers to automatically format files given certain properties such as:

```yml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix']
      - id: debug-statements
      - id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: forbid-new-submodules
``` 

The good news is that these modifications are backward compatible with the current `make` and `tox` configurations, running `$ make lint `, however, would generate something similar to the following:

![Screenshot from 2022-02-20 11-24-52](https://user-images.githubusercontent.com/62179149/154837647-71449c8e-82fa-424a-b835-8cb3eab439c4.png)

What do you think about adding `pre-commit`?
If y'all agree, I will be more than happy to open a PR.

**Comment by dbfreem** [comment]
@kclowes I made the change for buildTransaction build_transaction and estimateGas -> estimate_gas in the asyncify contract branch. I did deprecate the camelCase version but maybe since this is a move to v6 they could just be removed??

Also, I can take a pass at removing all the deprecated camelCase methods from geth and eth.

**Comment by kclowes** [comment]
Thank you so much, @dbfreem! 

> I did deprecate the camelCase version but maybe since this is a move to v6 they could just be removed??

They can be removed in v6 (master), but we'll need to add a deprecation warning in the v5 branch for the camelCase version.

> Also, I can take a pass at removing all the deprecated camelCase methods from geth and eth.

That would be great! I've been looking forward to getting that done!

**Comment by dbfreem** [comment]
Could ConciseContract and ImplicitContract be removed as part of v6?

**Comment by kclowes** [comment]
Yes! Thanks for the reminder!

**Comment by kclowes** [comment]
Explore raising a web3 specific error message rather than `ValueError` when method isn't available on the node: https://github.com/ethereum/web3.py/issues/2448

**Comment by kclowes** [comment]
Remove version module. All methods are implemented elsewhere.

**Comment by kclowes** [comment]
#2629 - make ipfshttpclient opt-in

**Comment by MartinThoma** [comment]
I see all checkmarks here set 🎉🥳

**Comment by MartinThoma** [comment]
I see that this is closed and `v7` is released, but `web3==6.0.0`  is not yet on PyPI.

Do you know when it will be? How is the procedure to decide when this will be?

I'm very excited about it, as web3 is currently blocking one of my projects from moving to Python 3.11 :sweat_smile:

**Comment by fselmo** [comment]
Hey @MartinThoma, we are in a code merge freeze and late testing phase just to make sure we don't need to make minor adjustments. If there are no complications, `v6.0.0` should be right around the corner 🙂.

**Comment by menaitm** [comment]
Hey @fselmo, please can you publish the code-frozen `v6.0.0` to PyPI as a `6.0.0-beta.11` or `rc`? I'd like to test against the code most likely to be released in v6

Thanks!

**Comment by kclowes** [comment]
The code frozen version is up as `v6.0.0-beta.11`. Let us know if you see anything!
