### ISSUE TITLE
``v7`` breaking changes megathread

### ISSUE THREAD

**Issue by fselmo** [ethereum/web3.py#2854]
Main thread for tracking breaking changes slated for the next major version release of web3.py - `v7`. This will be an evolving issue much like #1416 was for `v6`.

Candidates:

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/web3.py/issues/3188
- [ ] https://github.com/ethereum/web3.py/pull/2857
- [ ] #2685
- [ ] #2816
- [ ] #2849
- [ ] https://github.com/ethereum/web3.py/issues/3085
- [ ] https://github.com/ethereum/web3.py/pull/2964
- [ ] https://github.com/ethereum/web3.py/issues/3108
- [ ] https://github.com/ethereum/web3.py/issues/715
- [ ] https://github.com/ethereum/web3.py/issues/3115
- [ ] https://github.com/ethereum/web3.py/issues/901
- [ ] https://github.com/ethereum/web3.py/issues/3119
- [ ] https://github.com/ethereum/web3.py/issues/3175
- [ ] https://github.com/ethereum/web3.py/issues/3164
- [ ] https://github.com/ethereum/web3.py/issues/2844
- [ ] https://github.com/ethereum/web3.py/issues/3032
- [ ] #2884
- [ ] https://github.com/ethereum/web3.py/issues/2995
- [ ] https://github.com/ethereum/web3.py/issues/3021
```

**Comment by kclowes** [comment]
Return ipc path even if it doesn't yet exist. See #2911

**Comment by pacrob** [comment]
Remove the `ethPM` module, deprecated in #2953

**Comment by kclowes** [comment]
#2964 - Change provider User-Agent header to be more readable.

**Comment by kclowes** [comment]
Better UX for provider-specific middlewares. See: https://github.com/ethereum/web3.py/issues/2770

edit: issue created (#2990)

**Comment by reedsa** [comment]
Remove the miner API, deprecated in #2856.

**Comment by pacrob** [comment]
Here, then upstream libs:
 - Remove python 3.7 support
 - Branch name change: master -> main

**Comment by pacrob** [comment]
`AttributeDict` updates #3105

**Comment by pacrob** [comment]
web3 v7 should set `hexbytes>=1.0.0`.

Bottom pins for our other libs should move up to at least the release that dropped py37 support

**Comment by kclowes** [comment]
Where possible, have all errors thrown inherit from `Web3Exception`, or `ENSException`. See #1864.

**Comment by pacrob** [comment]
Bottom pins for deps should move up to those that drop py37:
eth-tester - `v0.10.2-b1`

        "eth-abi>=4.0.0",
        "eth-account>=0.8.0",
        "eth-hash[pycryptodome]>=0.5.1",
        "eth-typing>=3.0.0",
        "eth-utils>=2.1.0",
        "hexbytes>=0.1.0,<0.4.0",

**Comment by fselmo** [comment]
I updated the task list to include all the commented items in this issue. We can try to add items to the task list in the future so we can keep track of what's done and what isn't.

**Comment by fselmo** [comment]
> Return ipc path even if it doesn't yet exist. See #2911

@kclowes was this completed with the merging of #2911 ?

**Comment by pacrob** [comment]
> > Return ipc path even if it doesn't yet exist. See #2911
> 
> @kclowes was this completed with the merging of #2911 ?

Not done. Just needs the `if exists` part removed and return the path.

**Comment by fselmo** [comment]
All issues that were being tracked here are now completed and released as of `7.0.0-beta.5`. There may be other changes added into `v7` as we update the library to use newer major versions of dependencies but those can be tracked separately before stable gets released.

**Comment by MathiasExorde** [comment]
Can I see a link explaining the motivation for a major v7 changing lots of things?

**Comment by fselmo** [comment]
> Can I see a link explaining the motivation for a major v7 changing lots of things?

Hey @MathiasExorde. Each issue here should have its own link, though the [migration documentation](https://github.com/ethereum/web3.py/blob/main/docs/migration.rst#migrating-from-v6-to-v7) provides a good summary of it all together. Most of the changes were quite small, though technically breaking. Those have to be aggregated and need to wait until the next major version cycle to be addressed. Some of the bigger changes, like the middleware moving to a class-based architecture, helped close out long-standing tickets such as the ability to batch requests which had been an [open issue since 2018](https://github.com/ethereum/web3.py/issues/832). Hope that helps.
