### ISSUE TITLE
Auto-detect providers if none provided to Web3

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#485]
* Version: 4

### What was wrong?

More and more functions are valuable even if not connected to a node. Initializing with no providers available would be helpful to access those functions.

Additionally, it would be natural to try to auto-detect providers if none are provided, equivalent to how `from web.auto import w3` works.

#### Todo

- [x] Review/improve error message when trying to connect to one of the providers and it is unavailable.
- [x] add default value to `providers` in `Web3` and `Manager`, to put the request manager in a special auto-detect mode
- [x] move autodetection logic from `web3.auto` into `web3.providers.auto`
- [x] auto-detect mode: save last-working provider to reattempt first
- [x] auto-detect mode: if no previously-working provider, or last-working is unavailable, re-attempt detection
~- [ ] auto-detect mode: if failure to detect, raise an exception describing it different from the first case~
- [x] auto-detect mode: look up environment variable first
- [x] replace `web3.auto.w3` implementation with `w3 = Web3()`
- [x] map environment URI to provider

#### Specifying No Providers

To prevent connection to any node, allow initialization of `Web3` with `None` provider specified. This is already technically supported, it just fails with unhelpful error messages at the moment.

```
from web3 import Web3
w3 = Web3(providers=None)
# or simply
w3 = Web3(None)
```

If any call attempt is made, it will always fail with an error saying that `Web3` explicitly disallows node interaction when started with `Web3(providers=None)`.

#### Auto-detecting Providers

To auto-detect providers, allow initialization of `Web3` with no provider specified:

```
from web3 import Web3
w3 = Web3()
```

A `Web3` instance is returned immediately, and can be used for anything that does not interact with the node.

The first time a call to a node is attempted, it tries to auto-detect a node. If one is found, save it for later use and automatically reuse it. In this mode, any time the connection fails, it will try to reconnect to any node that it can find.

#### Auto-detection in `web3.auto.w3`

```
from web3.auto import w3
```

Will now be exactly equivalent to:

```
from web3 import Web3
w3 = Web3()
```

That means two changes:

1. If no nodes are found, the import still succeeds and works for functions that don't need node interaction
2. If a node is not found at import time, `w3` will attempt to re-detect it on every attempt to call to the node

#### Explicitly Setting Providers

*No change in functionality*

For the normal use case (previously, the only explicitly supported use case), `Web3` would only attempt to use the providers specified. If none of them are available, it will **not** attempt to auto-detect another one. (If you try to connect to a testnet node and fail, we don't want to automatically connect you to a production node without you realizing)

**Comment by pipermerriam** [comment]
Might be nice if it was possible to configure with environment variables as well.  Allows changing provider configurations without having to change code.

**Comment by carver** [comment]
Perhaps something like:
```sh
WEB3_PROVIDER="http://localhost:8545"
# or
WEB3_PROVIDER="file:///home/$USER/.ethereum/geth.ipc"
```

**Comment by pipermerriam** [comment]
maintain a mapping of the protocol `http/file/???` to built-in provider classes?  Totally functional and simple.  I'd like to try and figure out a longhand that will also allow for 3rd party providers to be specified this way.  Maybe we can have a special version something like this.

```
provider://dot.separated.import_path.to.ProviderClass
```

That would handle most standard use cases as long as the provider class doesn't require initialization parameters.  We could *in-theory* also allow for parsing of query parameters off the URI that would be sent in as `*kwargs` for fancier use cases...  (I'm potentially over-engineering this but it's a starting point)
